cases/urls.py
from django.urls import path
from .views import (CasesListView,
                     CaseDetailView, 
                     CaseUpdateView, 
                     CaseDeleteView, 
                     CaseCreateView)


urlpatterns = [
    path("", CasesListView.as_view(), name="cases_list"),
    path("<slug:slug>/", CaseDetailView.as_view(), name="case_detail"),
    path("<slug:slug>/edit", CaseUpdateView.as_view(), name="case_edit"),
    path("<slug:slug>/delete", CaseDeleteView.as_view(), name="case_delete"),
    path("new", CaseCreateView.as_view(), name="case_new"),
    
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("pages.urls")),
    path("cases/", include("cases.urls")),
###
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]

cases/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Case(models.Model):
    verified=models.BooleanField(default=False, )
    slug = models.SlugField(
        ("Link"),
        max_length=40,
        null=False,
        blank=False,
        unique=True,
        help_text="لینک مورد علاقه برای کیس خود را وارد کنید. تلاش کنید لینکتان گویا و دقیق باشد، پس از این توانایی تغییر آن را نخواهید داشت.",
    )

    rts={"ریه":"ریه",
         "هماتولوژی و انکولوژی":"هماتولوژی و انکولوژی",
         "روماتولوژی":"روماتولوژی",
         "غدد":"غدد",
         "گوارش":"گوارش",
         "نفرولوژی":"نفرولوژی",
         "جنرال":"جنرال",
         "قلب":"قلب",
         "پوست":"پوست",
         "اطفال":"اطفال",
         "زنان":"زنان",
         "اعصاب":"اعصاب",
         "روان":"روان",
         "ENT":"ENT",
         "عفونی":"عفونی",
         "چشم":"چشم",
         "مسمومین":"مسمومین",}
    title = models.CharField(
        max_length=50,
        null=False,
        blank=False,
    )
    cat=models.CharField(
        ("دسته:"),
        max_length=100,
        choices=rts,
        null=True,
        blank=True,

    )


    description = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        help_text="خلاصه‌ای برای نشان دادن در صفحۀ اصلی که می‌تواند از عنوان طولانی‌تر باشد (تا دویست حرف)."
    )
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    pretext = models.TextField(null=True, blank=True,help_text="اگر خواستید، می‌توانید مقدمه‌ای دربارۀ شرح‌حال خود بنویسید.")

    gender = models.CharField(
        max_length=5,
        choices={"آقا": "Male", "خانم": "Female", "دیگر": "Other"},
        null=False,
        blank=False,
        default="O",
    )
    location = models.CharField(
        max_length=10,
        choices={
            "مطب": "مطب",
            "درمانگاه": "درمانگاه",
            "اورژانس": "اورژانس",
            "بخش": "بخش",
        },
        null=False,
        blank=False,
        default="ROT",
    )
    job = models.CharField(max_length=20, null=True, blank=True)
    dwelling = models.CharField(max_length=20, null=True, blank=True)
    age = models.PositiveSmallIntegerField(null=False, blank=False, default=40)
    marriage = models.CharField(
        max_length=15,
        choices={
            "متاهل": "متاهل",
            "مجرد": "مجرد",
            "همسر فوت شده": "همسر فوت شده",
            "جداشده": "جداشده",
        },
        null=True,
        blank=True,
    )
    # date_of_admission=models.DateField(null=True, blank=True)
    doctor = models.CharField(max_length=20, null=True, blank=True)
    source = models.CharField(max_length=10, null=True, blank=True)
    reliability = models.CharField(
        max_length=1,
        choices={
            "5": "5/5",
            "4": "4/5",
            "3": "3/5",
            "2": "2/5",
            "1": "1/5",
        },
        null=True,
        blank=True,
    )
    setting = models.CharField(max_length=30, null=True, blank=True)

    PR = models.DecimalField(
        max_digits=3, decimal_places=0, null=True, blank=True, default=70
    )
    BP_S = models.DecimalField(
        ("Systolic BP"),
        max_digits=3,
        decimal_places=0,
        null=True,
        blank=True,
        default=120,
    )
    BP_D = models.DecimalField(
        ("Diastolic BP"),
        max_digits=3,
        decimal_places=0,
        null=True,
        blank=True,
        default=80,
    )
    RR = models.DecimalField(
        max_digits=2, decimal_places=0, null=True, blank=True, default=18
    )
    SPO2_O = models.DecimalField(
        ("SPO2 With Oxygen"),
        max_digits=3,
        decimal_places=0,
        null=True,
        blank=True,
    )
    SPO2_N = models.DecimalField(
        ("SPO2 Without Oxygen"),
        max_digits=3,
        decimal_places=0,
        null=True,
        blank=True,
    )
    Temp = models.DecimalField(
        ("Temperature"),
        max_digits=2,
        decimal_places=0,
        null=True,
        blank=True,
        default=37,
    )

    cc = models.CharField(
        ("Cheif Complaint"), max_length=100, null=False, blank=False, default=""
    )
    pi = models.TextField(("Present Illness"), null=False, blank=False, default="")
    pmh = models.TextField(
        ("Past Medical History"),
        null=True,
        blank=True,
    )
    drg = models.TextField(
        ("Drugs and Addictions"),
        null=True,
        blank=True,
    )
    sh = models.TextField(
        ("Social History"),
        null=True,
        blank=True,
    )
    fh = models.TextField(
        ("Family History"),
        null=True,
        blank=True,
    )
    alg = models.CharField(
        ("Allergies"),
        max_length=100,
        null=True,
        blank=True,
    )
    phe = models.TextField(
        ("Physical Examinations and Review of Systems"),
        null=True,
        blank=True,
    )
    dat = models.TextField(
        ("Paraclinic Data"),
        null=True,
        blank=True,
        help_text=("Including Previous Lab Data and Images and ECGs."),
    )
    summary = models.TextField(
        null=True,
        blank=True,
    )
    pdx = models.CharField(
        ("Primary Dx"),
        max_length=100,
        null=True,
        blank=True,
    )
    act = models.TextField(
        ("Actions"),
        null=True,
        blank=True,
    )



    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("case_detail", args=[str(self.slug)])


class FollowUp(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    date = models.DecimalField(
        ("Days After Admission:"),
        max_digits=2,
        decimal_places=0,
        null=False,
        blank=False,
        default=0,
    )
    text = models.TextField(("Note"), null=False, blank=False, help_text="توجه کنید که نت‌ها در حال حاضر، قابل تغییر یا پاکسازی نیستند.")
    
    def get_absolute_url(self):
        return reverse("cases_list",kwargs={"slug": self.slug})
    
    def __str__(self):
        return (str(self.date)+" "+self.text[:32])

class Comment(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    verified=models.BooleanField(default=True)
    comment = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.comment[:32]

templates/about.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}
{% block content %}
<div dir="ltr">
<h3>Welcome to medepartout Website.</h3>
<h5>The Site is Under Construction. </h5>
<p> Medepartout is a platform dedicated to medic geeks, designed with the aim of dispatching medical insights across borders. Our mission is to foster collaboration and knowledge-sharing among students and experts in various fields, transcending geographical limitations.</p>

<p> Our initial offering features an app tailored for medical history-taking, crafted with the needs of specialists in mind. While our focus is niche, our aspirations are vast. We strive to cultivate a community where geeks :) can exchange ideas, stay updated on the latest developments, and elevate their practice to new heights.</p>
    
<p> As we navigate this journey, we remain grounded in our commitment to excellence. We understand the importance of continuous improvement and eagerly anticipate expanding our offerings to cater to the evolving needs of our community.</p>
    
<p> Join us as we embark on this journey to foster excellence and collaboration among learners worldwide. Together, let's harness the power of collective expertise to make a meaningful impact in our respective fields.</p>
    
<p> Thank you for being a part of the Medepartout community.</p>
<p>Check <a href= "{% url 'cases_list' %}" style="font-size:20px" class=""><b>Cases App</b></a></p>

<p style="color:gray;font-size:12px">The text above is written with free version of Chat-GPT with some modifications. </p>
</div>
{% endblock content %}

templates/base copy.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{% block title %}Hx | {% endblock title %}</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100..900&display=swap" rel="stylesheet">
<style>    
    .vazirmatn {
        font-family: "Vazirmatn", sans-serif;
        font-optical-sizing: auto;
        font-weight: 400;
        font-style: normal;
    }
    .marg {
        margin-right: 150px;
    }
    .sidebar {
        margin: 0;
        padding: 0;
        width: 150px;
        background-color: #f1f1f1;
        position: fixed;
        height: 100%;
        overflow: auto;
      }
      
      /* Sidebar links */
      .sidebar a {
        display: block;
        color: black;
        padding: 16px;
        text-decoration: none;
      }
      
      /* Active/current link */
      .sidebar a.active {
        background-color: #04AA6D;
        color: white;
      }
      
      /* Links on mouse-over */
      .sidebar a:hover:not(.active) {
        background-color: #555;
        color: white;
      }
      
      /* Page content. The value of the margin-left property should match the value of the sidebar's width property */
      div.content {
        margin-right: 150px;
        margin-left:150px;
        padding: 1px 16px;
        height: 1000px;
      }
      
      /* On screens that are less than 700px wide, make the sidebar into a topbar */
      @media screen and (max-width: 700px) {
        .sidebar {
          width: 100%;
          height: auto;
          position: relative;
        }
        .sidebar a {float: left;}
        div.content {margin-left: 0;}
      }
      
      /* On screens that are less than 400px, display the bar vertically, instead of horizontally */
      @media screen and (max-width: 400px) {
        .sidebar a {
          text-align: center;
          float: none;
        }
      }
    .margUp{
        margin-top:100px
    }
    .margLeft{
        margin-left:100px
    }

    .sidebarLeft {
        margin: 0;
        padding: 0;
        width: 150px;
        background-color: #f1f1f1;
        position: fixed;
        height: 100%;
        left:0px;
      }
      
      /* Sidebar links */
      .sidebarLeft a {
        display: block;
        color: black;
        padding: 16px;
        text-decoration: none;
      }
      
      /* Active/current link */
      .sidebar a.active {
        background-color: #04AA6D;
        color: white;
      }
      
      /* Links on mouse-over */
      .sidebarLeft a:hover:not(.active) {
        background-color: #555;
        color: white;
      }
      
      /* On screens that are less than 700px wide, make the sidebar into a topbar */
      @media screen and (max-width: 700px) {
        .sidebarLeft {
          width: 100%;
          height: auto;
          position: relative;
        }
        .sidebarLeft a {float: left;}
        div.content {margin-left: 0;}
      }
      
      /* On screens that are less than 400px, display the bar vertically, instead of horizontally */
      @media screen and (max-width: 400px) {
        .sidebarLeft a {
          text-align: center;
          float: none;
        }
      }
</style>

</head>
<body dir="rtl" class="content">
    
    <div class="sidebar" dir="ltr">
        <a class="active margUp" href="{% url 'cases_list' %}">All Cases</a>
        <a href="{% url 'case_new' %}">Add Yours</a>
    </div>

    <div class="sidebarLeft" dir="ltr">

    </div>

        <div class="container content ">
        <header class="p-3 mb-3 border-bottom margLeft" dir="ltr">
        <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center
        justify-content-lg-start">
        <a class="navbar-brand" href="{% url 'cases_list' %}">medepartout | Cases &emsp;</a>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center
        mb-md-0">
        {% if user.is_authenticated %}
        <li><a href="{% url 'case_new' %}" class="btn btn-outline-primary m-2" styles="padding: 2px;">+ Add &ensp;</a></li>
        </ul>
        <div class="dropdown text-end">
        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
        id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        {{ user.username }}
        </a>
        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item" href="{% url 'password_change'%}">
        Change password</a></li>
            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="dropdown-item">Log Out</button>
            </form></li>
        </ul>
        </div>
        {% else %}
        </ul>
        <div class="text-end">
        <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">
        Log In</a>
        <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
        </div>
        {% endif %}
        </div>
        </div>
        </header>
        <main dir='rtl' class="margLeft">
        <main dir='rtl' class="margLeft">
        {% block content %}
        {% endblock content %}
        </main>
        </div>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>

templates/case_delete.html
{% extends "base.html" %}
{% block content %}
<h1 dir="ltr">Delete</h1>
<form action="" method="post">{% csrf_token %}
<p>آیا از حذف
    <b>"{{ case.title }}"</b>
    اطمینان دارید؟</p>
<button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/case_detail copy.html
{% extends "base.html" %}

{% block content %}

<style>
    .paper{
        background-color:#eee;
        border-radius:5px;
        padding:10px
        display: grid;

    }
    .infoTable{
        padding:10px;
        display: grid;
        column-gap: 3px;
        grid-template-columns: 0.6fr 1fr 1fr 1fr 1fr;
        grid-template-rows: 1fr 1fr
    }
    .cell{
        border:1px;
    }
    .hx{
        background-color:#f9f9f9;
        padding:10px;
        margin:15px;
        border-radius:5px;
    }
    .editDelete{
        {% comment %} background-color:#f1f1f1; {% endcomment %}
        position:fixed;
        bottom:0px;
        padding:15px;
        right:0px;
        border-radius:10px;
    }
    a.float{
        margin-top:5px;
        margin-right: 5px;
        width:100px;
    }
    .vital{
        left:20px;
        width: 15%;
        background-color:#ffb;
        padding:10px;
        margin:15px;
        border-radius:5px;
        display: grid;
        column-gap: 3px;
        grid-template-columns: 0.6fr 1fr;
    }
    .hi {
        column-span: all;
    }
</style>

<div class="article-entry" style='margin-left:50px; margin-right:50px'>
<h2>{{ object.title }}</h2>
<p dir="ltr" style='margin-left:10px;'> {{ object.date_created|date:"d M y" }}  &emsp; By {{ case.author.first_name }} {{ case.author.last_name }} | {{ case.author.degree }} </p>
<p>{{ object.description|safe }}</p>
<p>
    {{ case.pretext|safe }}
</p>
<div class="paper">
    <h5 style="padding:15px 15px 0px 10px"> شرح حال و معاینۀ فیزیکی:</h5>
    <hr/>
    <div class="infoTable">
        <div class="cell"> جنسیت: {{ case.gender }} </div> 
        <div class="cell"> وضعیت زناشویی: {{ case.marriage }} </div> 
        <div class="cell"> پیشه: {{ case.job }} </div>
        <div class="cell"> پزشک معالج: {{ case.doctor }} </div>
        <div class="cell"> محل مراجعه: {{ case.location }} </div>

        <div class="cell">{{ case.age }} ساله </div>
        <div class="cell">منبع شرح حال: {{ case.source }} </div>
        <div class="cell"> محل زندگی: {{ case.dwelling }} </div>
        <div class="cell"> میزان قابل اعتماد بودن: {{ case.reliability }}/5</div>
        <div class="cell"> مرکز درمانی: {{ case.setting }} </div>
    </div>
    <div class="hx"><b>CC: </b>{{ case.cc }}</div>
    <div class="hx"><b>PI: </b>{{ case.pi }}</div>
    <div dir="ltr" class="vital">
        <div class="hi"><b>Vital Signs:</b></div><hr/>
        <div>PR: {{ case.PR }}</div>
        <div>BP: {{ case.BP_S }}/{{ case.BP_D }}</div>
        <div>RR: {{ case.RR }}</div>
    </div>
    <div class="hx"><b>PMH: </b>{{ case.pmh }}</div>
    {% if case.drg %}
    <div class="hx"><b>Drugs: </b>{{ case.drg }}</div>
    {% else %}
    <p style="margin:20px">بیمار دارو یا مدۀ ویژه‌ای مصرف <u>نمی‌کند</u>.</p>
    {% endif %}

    {% if case.sh %}
    <div class="hx"><b>SH: </b>{{ case.sh }}</div>
    {% else %}
    <p style="margin:20px">بیمار Social Historyای را ذکر <u>نمی‌کند</u>.</p>
    {% endif %}
    {% if case.fh %}
    <div class="hx"><b>FH: </b>{{ case.fh }}</div>
    {% else %}
    <p style="margin:20px">بیمار Family Historyای را ذکر <u>نمی‌کند</u>.</p>
    {% endif %}

    {% if case.alg %}
    <div class="hx"><b>Allergy: </b>{{ case.alg }}</div>
    {% else %}
    <p style="margin:20px">بیمار آلرژی‌ای را ذکر <u>نمی‌کند</u>.</p>
    {% endif %}

    <div class="hx"><b>Physical Examination and Review of Systems:</b> <br/>{{ case.phe }}</div>
    <div class="hx"><b>Other Data: </b><br/>{{ case.dat }}</div>
    <div class="hx"><b>Summary: </b>{{ case.summary }}</div>
    <div class="hx"><b>Primary Dx:</b> <br/>{{ case.pdx }}</div>
    <div class="hx"><b>Action:</b> <br/>{{ case.act }}</div>

</div>
    <hr/>
<p class="editDelete"><a href="{% url 'case_edit' case.slug %}" class="btn btn-warning float">ویرایش</a>
    <br/>
<a href="{% url 'case_delete' case.slug %}" class="btn btn-danger float">حذف</a>
<br/>
{%if case.followup_set.all %}
<div class="paper">
    <h5 style="margin:15px">یادداشت‌های روزانه و پیگیری‌ها:</h5>
{% for note in case.followup_set.all %}
<div class="hx">
    <span class="font-weight-bold">
    <h6>روز {{ note.date }} پس از بستری: </h6>
    </span>
    {{ note.text }}
</div>
{% endfor %}
{%else%}
<span></span>
{%endif%}

</div>
<br/>
</div>

{% endblock content %}

templates/case_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

{% block content %}
{% if case.verified %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% comment %} <div class="article-entry" style='margin-left:50px; margin-right:50px'> {% endcomment %}
<h2>{{ object.title }}</h2>
<p dir="ltr" style='margin-left:10px;'> {{ object.date_created|date:"d M y" }}  &emsp; By {{ case.author.first_name }} {{ case.author.last_name }} | {{ case.author.degree }} </p>
<p style='margin-right:10px;'>
    {{ case.pretext|safe }}
</p>
<div class="paper">
    <h5 class='spanTwo' style="padding:15px 15px 0px 10px"> شرح حال و معاینۀ فیزیکی:</h5>
    <hr/ class="spanTwo">
    <div class="infoTable spanTwo">
        <div class="cell"> جنسیت: {{ case.gender }} </div> 
        <div class="cell"> وضعیت زناشویی: {{ case.marriage }} </div> 
        <div class="cell"> پیشه: {{ case.job }} </div>
        <div class="cell"> پزشک معالج: {{ case.doctor }} </div>
        <div class="cell"> محل مراجعه: {{ case.location }} </div>
        <hr/ class="myHR" style="grid-column: span 5;">
        <div class="cell">{{ case.age }} ساله </div>
        <div class="cell">منبع شرح حال: {{ case.source }} </div>
        <div class="cell"> محل زندگی: {{ case.dwelling }} </div>
        <div class="cell"> میزان قابل اعتماد بودن: {{ case.reliability }}/5</div>
        <div class="cell"> مرکز درمانی: {{ case.setting }} </div>
    </div>
    <div class="hx"><b>CC: </b>{{ case.cc }}</div>

    {% if case.PR or case.BP_S or case.RR or case.Temp %}
        <div dir="ltr" class="vital">
        <div class="spanTwo vsText"><b>Vital Signs:</b></div>
        <div>PR: {{ case.PR }}</div>
        <div>BP: {{ case.BP_S }}/{{ case.BP_D }}</div>
        <div>RR: {{ case.RR }}</div>
        {% if case.SPO2_O %}
        <div>SP<sub>O&#8322;</sub>: {{ case.SPO2_O }}</div>
        {% endif %}
        <div>T: {{ case.Temp }}&#176;C</div>
        {% if case.SPO2_O %}
        <div>SP<sub>O&#8322;</sub><i>With</i> O&#8322;: {{ case.SPO2_N }}</div>
        {% endif %}
    </div>
    {% else %}
    <div dir="ltr" class="vital">
        <div class="spanTwo"><b>No Vital Sign Recorded</b></div>
    </div>
    {% endif %}
    <div class="hx"><b>PI: </b>{{ case.pi }}</div>

    <div class="hx"><b>PMH: </b>{{ case.pmh }}</div>
    {% if case.drg %}
    <div class="hx"><b>Drugs: </b>{{ case.drg }}</div>
    {% else %}
    <p style="margin:20px">بیمار دارو یا مادۀ ویژه‌ای مصرف <u>نمی‌کند</u>.</p>
    {% endif %}

    {% if case.sh %}
    <div class="hx"><b>SH: </b>{{ case.sh }}</div>
    {% else %}
    <p style="margin:20px">بیمار Social Historyای را ذکر <u>نمی‌کند</u>.</p>
    {% endif %}


    {% if case.alg %}
    <div class="hx"><b>Allergy: </b>{{ case.alg }}</div>
    {% else %}
    <p style="margin:20px">بیمار آلرژی‌ای را ذکر <u>نمی‌کند</u>.</p>
    {% endif %}

    {% if case.fh %}
    <div class="hx"><b>FH: </b>{{ case.fh }}</div>
    {% else %}
    <p style="margin:20px">بیمار Family Historyای را ذکر <u>نمی‌کند</u>.</p>
    {% endif %}

    <div class="hx"><b>Other Data: </b><br/>{{ case.dat }}</div>
    <div class="hx"><b>Physical Examination and Review of Systems:</b> <br/>{{ case.phe }}</div>
    <div class="hx" style="background-color:#ffd"><b>Summary: </b>{{ case.summary }}</div>
    <div class="hx"><b>Primary Dx:</b> <br/>{{ case.pdx }}</div>
    <div class="hx"><b>Action:</b> <br/>{{ case.act }}</div>

</div>
    <hr/>

{% comment %} {%if case.followup_set.all %}
<div class="paper">
    <h5 style="margin:15px">یادداشت‌های روزانه و پیگیری‌ها:</h5>
{% for note in case.followup_set.all %}
<div class="hx spanTwo">
    <span class="font-weight-bold">
    <h6>روز {{ note.date }} پس از بستری: </h6>
    </span>
    {{ note.text }}
</div>
{% endfor %}
{%else%}
<span></span>
{%endif%} 
 </div>
{% if user.username == case.author.username %}
<h4 class="mt-3">Add a Daily Note</h4>
<form action="" method="post" >{% csrf_token %}
{{ form|crispy }}
<button class="btn btn-success ml-2" type="submit">Save</button>
</form>
{%endif%}
<br/> <hr>
<div> {% endcomment %}
    <h4>Comments</h4>
    {% for comment in case.comment_set.all %}
    <p>{{ comment.author }} &middot; {{ comment }}</p>
    {% endfor %}
    <hr>
</div>
<div>
<h4>Add a comment</h4>
<form action="" method="post">{% csrf_token %}
{{ form|crispy }}
<button class="btn btn-success ml-2" type="submit">Save</button>
</form>
</div>
{% else %}
<h2>این مطلب هنوز به تایید ادمین نرسیده است.</h2>

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<br/><br/><br/><br/><br/><br/><br/>

{% endif %}
{% endblock content %}

{% block sidebarLeft %}
{% if user.username == case.author.username %}

<div class="editDelete"><a href="{% url 'case_edit' case.slug %}" class="btn btn-warning">ویرایش</a>
    <a href="{% url 'case_delete' case.slug %}" class="btn btn-danger">حذف</a></div>
{% endif %}
{% endblock sidebarLeft %}

templates/case_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<h1>کیس جدید</h1>

<form action="" method="post">{% csrf_token %}
<div class="createForm" autocomplete="off">
    {{ form|crispy }}
<button class="btn btn-success ml-2" type="submit" id="save" hidden>Save</button>
</div>
</form>
{% endblock content %}

{% block sidebarLeft %}

<button type="submit" class="btn btn-success ml-2 fix editDelete"
       id="saveSecond" 
       onclick="document.getElementById('save').click()">Save</button>
{% endblock sidebarLeft%}

templates/cases_list.html
{% extends "base.html" %}
{% block title %}Cases{% endblock title %}
{% block content %}
{% for case in case_list reversed %}
{% if case.verified and case.slug %}
<div class="card vazirmatn">
<div dir="rtl" class="card-header">
<a href="{% url 'case_detail' case.slug %}"><span class="font-weight-bold">{{ case.title }}</span></a> &emsp; &middot; &emsp;
<span dir="ltr" styles="display: flex; justify-content: center;" class="text-muted"> {{ case.date_created|date:"d M"  }}   &emsp; By {{ case.author.first_name }} {{ case.author.last_name }} | {{ case.author.degree }}
</span>
</div>
<div dir="rtl" class="card-body">
{{ case.description|safe }}
</div>
<div class="card-footer text-left text-muted" dir='ltr'>
    {{ case.followup|length }} Daily Notes | {{ case.comment|length }} Comments
{% if user.username == case.author.username %}
<a href="{% url 'case_edit' case.slug %}">Edit</a> | 
<a href="{% url 'case_delete' case.slug %}">Delete</a>
{% endif %}

{% comment %} {% if case.followup|length == 0 %}
No Daily Note Added
{%elif case.followup|length == 1 %}
1 Daily Note
{%else%} {% endcomment %}

{% comment %} {%endif%} {% endcomment %}
</div>
</div>
<br />
{% endif %}
{% endfor %}
{% endblock content %}